# Generated by Django 6.0.3 on 2026-04-06 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_articleview_articleviewdaily_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('demonetized', 'Demonetized'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('monetization_enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('demonetized_at', models.DateTimeField(blank=True, null=True)),
                ('payout_email', models.EmailField(blank=True, max_length=254)),
                ('payout_notes', models.TextField(blank=True)),
                ('policy_strikes', models.PositiveSmallIntegerField(default=0)),
                ('earnings_balance_cents', models.BigIntegerField(default=0)),
                ('lifetime_earnings_cents', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_creator_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorPayoutCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('scheduled_processing_date', models.DateField(help_text='Should stay within 10 days after the cycle closes.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='open', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_creator_payout_cycle_window')],
            },
        ),
        migrations.CreateModel(
            name='CreatorEarningsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ad_impression', 'Ad Impression'), ('ad_click', 'Ad Click'), ('adjustment', 'Adjustment'), ('payout', 'Payout'), ('reversal', 'Reversal')], db_index=True, max_length=30)),
                ('amount_cents', models.BigIntegerField()),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_earnings_entries', to='articles.articles')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_entries', to='creators.contentcreatoraccount')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['creator', 'occurred_at'], name='creators_cr_creator_56dfa5_idx'), models.Index(fields=['entry_type', 'occurred_at'], name='creators_cr_entry_t_7a4438_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('held', 'Held')], db_index=True, default='pending', max_length=20)),
                ('payable_on', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='creators.contentcreatoraccount')),
                ('payout_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_payouts', to='creators.creatorpayoutcycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'payable_on'], name='creators_cr_status_b52f2d_idx'), models.Index(fields=['creator', 'status'], name='creators_cr_creator_9c84a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('creator', 'payout_cycle'), name='unique_creator_payout_per_cycle')],
            },
        ),
        migrations.CreateModel(
            name='CreatorPerformanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('unique_views', models.PositiveBigIntegerField(default=0)),
                ('comments_count', models.PositiveBigIntegerField(default=0)),
                ('ratings_count', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('engagement_count', models.PositiveBigIntegerField(default=0)),
                ('revenue_cents', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_daily_performance', to='articles.articles')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='creators.contentcreatoraccount')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['creator', 'date'], name='creators_cr_creator_39d9e2_idx'), models.Index(fields=['article', 'date'], name='creators_cr_article_ef2647_idx')],
                'constraints': [models.UniqueConstraint(fields=('creator', 'article', 'date'), name='unique_creator_daily_performance_record')],
            },
        ),
    ]
