# Generated by Django 6.0.3 on 2026-04-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='media_assets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='share_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='subscriber_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentcreatoraccount',
            name='watch_time_minutes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreatorAudienceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('subscribers_total', models.PositiveBigIntegerField(default=0)),
                ('new_subscribers', models.PositiveBigIntegerField(default=0)),
                ('returning_viewers', models.PositiveBigIntegerField(default=0)),
                ('unique_viewers', models.PositiveBigIntegerField(default=0)),
                ('shares', models.PositiveBigIntegerField(default=0)),
                ('top_country', models.CharField(blank=True, max_length=100)),
                ('most_active_hour_label', models.CharField(blank=True, max_length=50)),
                ('watch_time_minutes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_daily', to='creators.contentcreatoraccount')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['creator', 'date'], name='creators_cr_creator_76cd61_idx')],
                'constraints': [models.UniqueConstraint(fields=('creator', 'date'), name='unique_creator_audience_daily_record')],
            },
        ),
    ]
