# Generated by Django 6.0.3 on 2026-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_plan_disabled_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['incomplete', 'active', 'past_due'])), fields=('customer',), name='unique_open_subscription_per_customer'),
        ),
    ]
