# Generated by Django 6.0.4 on 2026-05-06 01:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_image'),
        ),
    ]
