# Generated by Django 6.0.4 on 2026-05-08 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilepost_share_count_profilepostshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['-is_featured', 'sort_order', 'created_at']},
        ),
        migrations.AddIndex(
            model_name='profileimage',
            index=models.Index(fields=['user', 'sort_order', 'created_at'], name='profiles_pr_user_id_4f45ca_idx'),
        ),
        migrations.AddIndex(
            model_name='profileimage',
            index=models.Index(fields=['user', 'is_featured'], name='profiles_pr_user_id_de0e3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('user',), name='unique_featured_profile_image_per_user'),
        ),
    ]
