# Generated by Django 6.0.4 on 2026-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profileimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilestats',
            name='article_likes_given_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilestats',
            name='comments_written_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilestats',
            name='post_likes_given_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilestats',
            name='weekly_activity_series',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
