# Generated by Django 6.0.4 on 2026-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofilestats_article_likes_given_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilestats',
            name='post_shares_given_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
