# Generated by Django 6.0 on 2026-01-01 23:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1x1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image1x1')),
                ('image4x3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4x3')),
                ('image16x9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image16x9')),
                ('title', models.CharField(max_length=200)),
                ('altImage', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('briefsummary', models.TextField()),
                ('badgeColor', models.CharField(blank=True, max_length=200, null=True)),
                ('featuredType', models.CharField(blank=True, max_length=200, null=True)),
                ('videoLink', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('videoType', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
