# Generated by Django 5.2.11 on 2026-04-03 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('embed', 'Embed'), ('other', 'Other')], db_index=True, default='web', max_length=20)),
                ('is_counted', models.BooleanField(db_index=True, default=False)),
                ('is_unique', models.BooleanField(db_index=True, default=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleViewDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('unique_views_count', models.PositiveBigIntegerField(default=0)),
                ('counted_views_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='articles',
            name='counted_views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='unique_views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rating_articles', through='articles.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_records', to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['article', 'created_at'], name='articles_ra_article_bf1332_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'created_at'], name='articles_ra_user_id_575253_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_rating'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='articles.articles'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_view_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleviewdaily',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_view_stats', to='articles.articles'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'created_at'], name='articles_ar_article_7cb1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'user', 'created_at'], name='articles_ar_article_53be0c_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'session_key', 'created_at'], name='articles_ar_article_64dfba_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'ip_address', 'created_at'], name='articles_ar_article_69aaca_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'is_counted', 'created_at'], name='articles_ar_article_6b7913_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'is_unique', 'created_at'], name='articles_ar_article_1455a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleview',
            constraint=models.CheckConstraint(condition=models.Q(('watched_seconds__gte', 0)), name='articleview_watched_seconds_gte_0'),
        ),
        migrations.AddIndex(
            model_name='articleviewdaily',
            index=models.Index(fields=['article', 'date'], name='articles_ar_article_89c829_idx'),
        ),
        migrations.AddIndex(
            model_name='articleviewdaily',
            index=models.Index(fields=['date'], name='articles_ar_date_104956_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleviewdaily',
            constraint=models.UniqueConstraint(fields=('article', 'date'), name='unique_article_daily_view_stat'),
        ),
    ]
