# Generated by Django 6.0.4 on 2026-05-20 13:52

from django.db import migrations, models


def normalize_nullable_text_fields(apps, schema_editor):
    Articles = apps.get_model("articles", "Articles")
    ArticleView = apps.get_model("articles", "ArticleView")

    Articles.objects.filter(badgeColor__isnull=True).update(badgeColor="")
    Articles.objects.filter(featuredType__isnull=True).update(featuredType="")
    Articles.objects.filter(videoLink__isnull=True).update(videoLink="")
    Articles.objects.filter(body__isnull=True).update(body="")
    Articles.objects.filter(videoType__isnull=True).update(videoType="")

    ArticleView.objects.filter(session_key__isnull=True).update(session_key="")
    ArticleView.objects.filter(user_agent__isnull=True).update(user_agent="")


def noop_reverse(apps, schema_editor):
    # Data normalization is intentionally one-way to enforce consistency.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleview_articleviewdaily_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_nullable_text_fields, noop_reverse),
        migrations.AlterField(
            model_name='articles',
            name='badgeColor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='featuredType',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='videoLink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='videoType',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
