sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,staticfiles/**,**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=**/tests/**/*.py,**/test_*.py,manage.py,config/settings_test.py
sonar.cpd.exclusions=**/tests/**/*.py,**/test_*.py
