sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,staticfiles/**,staticfiles/**/*,**/staticfiles/**,**/staticfiles/**/*,media/**,**/media/**,**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=**/tests/**/*.py,**/test_*.py,manage.py,config/settings_test.py
sonar.cpd.exclusions=**/tests/**/*.py,**/test_*.py
