# Generated by Django 6.0.3 on 2026-04-09 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleview_articleviewdaily_and_more'),
        ('comments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='comments.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['article', 'created'], name='comments_co_article_4b44e9_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['user', 'created'], name='comments_co_user_id_388753_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['parent', 'created'], name='comments_co_parent__a2b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['root', 'created'], name='comments_co_root_id_1fa90c_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['active', 'created'], name='comments_co_active_d9dd4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='comment_cannot_reply_to_self'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comments'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'created'], name='comments_co_comment_7a3999_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', 'created'], name='comments_co_user_id_325efe_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_like_per_user'),
        ),
    ]
