# Generated by Django 6.0.4 on 2026-05-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentlike_comments_like_count_comments_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='comments.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['comment', 'created'], name='comments_co_comment_fc04c9_idx'), models.Index(fields=['user', 'created'], name='comments_co_user_id_9cc5fc_idx'), models.Index(fields=['status', 'created'], name='comments_co_status_ee4898_idx')],
            },
        ),
    ]
