# Generated by Django 6.0.3 on 2026-04-06 23:56

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('placement_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('homepage', 'Homepage'), ('sidebar', 'Sidebar'), ('banner', 'Banner'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('pricing_model', models.CharField(choices=[('cpm', 'CPM'), ('cpc', 'CPC')], db_index=True, default='cpm', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('budget_cents', models.PositiveBigIntegerField(default=0)),
                ('daily_budget_cents', models.PositiveBigIntegerField(default=0)),
                ('cpm_rate_cents', models.PositiveIntegerField(default=0)),
                ('cpc_rate_cents', models.PositiveIntegerField(default=0)),
                ('target_url', models.URLField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creative_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('html', 'HTML')], default='image', max_length=20)),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ad_creative')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=100)),
                ('destination_url', models.URLField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertising.advertisingcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingPartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('preferred_billing_model', models.CharField(choices=[('cpm', 'CPM'), ('cpc', 'CPC'), ('mixed', 'Mixed')], default='cpm', max_length=10)),
                ('dashboard_enabled', models.BooleanField(default=True)),
                ('fraud_monitoring_enabled', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_partner_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.advertisingpartneraccount'),
        ),
        migrations.CreateModel(
            name='CampaignPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='advertising.advertisingcampaign')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_placements', to='advertising.adplacement')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPerformanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('billable_impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('billable_clicks', models.PositiveBigIntegerField(default=0)),
                ('engagements', models.PositiveBigIntegerField(default=0)),
                ('invalid_clicks', models.PositiveBigIntegerField(default=0)),
                ('spend_cents', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='advertising.adcreative')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_performance', to='advertising.adplacement')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='advertising.advertisingcampaign')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='advertising_date_2e92ac_idx'), models.Index(fields=['campaign', 'date'], name='advertising_campaig_266625_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'creative', 'placement', 'date'), name='unique_ad_daily_performance_record')],
            },
        ),
        migrations.AddIndex(
            model_name='advertisingcampaign',
            index=models.Index(fields=['status', 'pricing_model'], name='advertising_status_cb3aed_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisingcampaign',
            index=models.Index(fields=['start_at', 'end_at'], name='advertising_start_a_3a249f_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignplacement',
            constraint=models.UniqueConstraint(fields=('campaign', 'placement'), name='unique_campaign_placement'),
        ),
    ]
