# Generated by Django 6.0.3 on 2026-04-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='average_ctr',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='current_balance_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='last_funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='monthly_spend_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='total_clicks',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='total_impressions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisingpartneraccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdvertisingAudienceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('conversions', models.PositiveBigIntegerField(default=0)),
                ('spend_cents', models.PositiveBigIntegerField(default=0)),
                ('top_placement_code', models.CharField(blank=True, max_length=100)),
                ('top_campaign_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_daily', to='advertising.advertisingpartneraccount')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['partner', 'date'], name='advertising_partner_9c9644_idx')],
                'constraints': [models.UniqueConstraint(fields=('partner', 'date'), name='unique_advertising_audience_daily_record')],
            },
        ),
    ]
