"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
import ast
from datetime import timedelta
import certifi
import ssl
from celery.schedules import crontab
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from opentelemetry.instrumentation.django import DjangoInstrumentor


def _parse_bool_env(name, default=False):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


def _parse_list_env(name, default=None):
    raw_value = os.getenv(name)
    if not raw_value:
        return default[:] if isinstance(default, list) else (default or [])
    return ast.literal_eval(raw_value)


def _parse_regex_list_env(name, default=None):
    raw_value = os.getenv(name)
    if not raw_value:
        return default[:] if isinstance(default, list) else (default or [])
    return ast.literal_eval(raw_value)


def _parse_ssl_cert_reqs(name, default):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default

    mapping = {
        "NONE": ssl.CERT_NONE,
        "OPTIONAL": ssl.CERT_OPTIONAL,
        "REQUIRED": ssl.CERT_REQUIRED,
    }
    return mapping.get(raw_value.strip().upper(), default)


def _build_allowed_origins(hosts):
    origins = []
    for host in hosts:
        clean_host = (host or "").strip()
        if not clean_host or clean_host == "*":
            continue
        clean_host = clean_host.lstrip(".")
        if "*" in clean_host:
            continue
        origins.append(f"https://{clean_host}")
    return origins


# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG')))
IS_PRODUCTION = not DEBUG
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
BILLING_TIME_ZONE = os.getenv("BILLING_TIME_ZONE", "America/New_York")
BILLING_DUNNING_RETRY_DAYS = int(os.getenv("BILLING_DUNNING_RETRY_DAYS", "1"))
BILLING_DUNNING_MAX_FAILURES = int(os.getenv("BILLING_DUNNING_MAX_FAILURES", "3"))
STRIPE_WEBHOOK_TOLERANCE_SECONDS = int(os.getenv("STRIPE_WEBHOOK_TOLERANCE_SECONDS", "300"))
SECURITY_ALERT_WINDOW_SECONDS = int(os.getenv("SECURITY_ALERT_WINDOW_SECONDS", "300"))
SECURITY_THROTTLE_ALERT_THRESHOLD = int(os.getenv("SECURITY_THROTTLE_ALERT_THRESHOLD", "25"))
SECURITY_WEBHOOK_BLOCK_ALERT_THRESHOLD = int(os.getenv("SECURITY_WEBHOOK_BLOCK_ALERT_THRESHOLD", "10"))
GRAPHQL_ALLOW_INTROSPECTION = _parse_bool_env("GRAPHQL_ALLOW_INTROSPECTION", DEBUG)
GRAPHQL_POST_ONLY_IN_PRODUCTION = _parse_bool_env("GRAPHQL_POST_ONLY_IN_PRODUCTION", True)

ALLOWED_HOSTS = _parse_list_env('ALLOWED_HOSTS')
DEFAULT_ALLOWED_ORIGINS = _build_allowed_origins(ALLOWED_HOSTS)
PAYMENT_RETURN_URL_ALLOWED_HOSTS = [
    host.lstrip(".")
    for host in ALLOWED_HOSTS
    if host and host != "*" and "*" not in host
]
STRIPE_WEBHOOK_IP_ALLOWLIST = [
    ip.strip()
    for ip in _parse_list_env("STRIPE_WEBHOOK_IP_ALLOWLIST", [])
    if isinstance(ip, str) and ip.strip()
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_cleanup.apps.CleanupConfig',
    'celery',
    'django_celery_beat',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'adrf',
    'drf_spectacular',
    'django_filters',
    'cloudinary',
    'graphene_django',
    "django_extensions",

    'users',
    'articles',
    'advertising',
    'creators',
    'comments',
    'profiles.apps.ProfilesConfig',
    'messaging',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address":os.getenv('REDISS_ADDRESS'),
                "ssl_cert_reqs": _parse_ssl_cert_reqs(
                    "REDIS_SSL_CERT_REQS",
                    ssl.CERT_REQUIRED if IS_PRODUCTION else ssl.CERT_NONE,
                ),
                "ssl_ca_certs": certifi.where(),
            }],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': int(os.getenv('DB_PORT')),
        'URL': os.getenv('DB_URI')
    }
}

# Temporary test DB override for local/dev environments without create-db permissions.
# Enable with USE_SQLITE_TEST_DB=1 when running tests.
if _parse_bool_env("USE_SQLITE_TEST_DB", False) and any(arg == "test" for arg in sys.argv):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(BASE_DIR / "test.sqlite3"),
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/staticfiles/'
# MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "users.Users"

CELERY_BROKER_URL = os.getenv('BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('REDISS_ADDRESS')
CELERY_SSL_CERT_REQS = _parse_ssl_cert_reqs(
    "CELERY_SSL_CERT_REQS",
    ssl.CERT_REQUIRED if IS_PRODUCTION else ssl.CERT_NONE,
)
REDIS_SSL_CERT_REQS = _parse_ssl_cert_reqs(
    "REDIS_SSL_CERT_REQS",
    ssl.CERT_REQUIRED if IS_PRODUCTION else ssl.CERT_NONE,
)
REDIS_SSL_CA_CERTS = certifi.where()
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_USE_SSL = {
    'ca_certs': certifi.where(),
    'cert_reqs': CELERY_SSL_CERT_REQS,
}
CELERY_REDIS_BACKEND_USE_SSL = {
    'ssl_cert_reqs': REDIS_SSL_CERT_REQS,
    'ssl_ca_certs': REDIS_SSL_CA_CERTS,
}
CELERY_BEAT_SCHEDULE = {
    'flush_expired_tokens': {
        'task': 'users.tasks.maintenance.flush_expired_tokens',
        'schedule':crontab(minute=0, hour=0, day_of_month='1,15'),
        'args': ()
    },
    'collect_due_recurring_payments': {
        'task': 'payments.tasks.collect_due_recurring_payments',
        'schedule': crontab(minute=1, hour=0),
        'args': ()
    },
}
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000  # 200MB
CELERY_BROKER_POOL_LIMIT = 1  # Standard for free CloudAMQP
CELERY_BROKER_CONNECTION_TIMEOUT = 30

GRAPHENE = {
    "SCHEMA": "schemas.schema.schema"
}

CORS_ALLOWED_ORIGINS = _parse_list_env('CORS_ALLOWED_ORIGINS', DEFAULT_ALLOWED_ORIGINS)
CORS_ALLOWED_ORIGIN_REGEXES = _parse_regex_list_env('CORS_ALLOWED_ORIGIN_REGEXES', [])
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-signup-client",
]
CSRF_TRUSTED_ORIGINS = _parse_list_env('CSRF_TRUSTED_ORIGINS', CORS_ALLOWED_ORIGINS)

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

GRAPHQL_ENABLE_GRAPHIQL = DEBUG

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _parse_bool_env("SECURE_HSTS_INCLUDE_SUBDOMAINS", IS_PRODUCTION)
SECURE_HSTS_PRELOAD = _parse_bool_env("SECURE_HSTS_PRELOAD", False)



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated'
        if IS_PRODUCTION
        else 'rest_framework.permissions.AllowAny',
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "common.exceptions.api_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "payment_checkout": os.getenv("PAYMENT_CHECKOUT_THROTTLE_RATE", "20/hour"),
        "payment_status": os.getenv("PAYMENT_STATUS_THROTTLE_RATE", "120/hour"),
        "auth_login": os.getenv("AUTH_LOGIN_THROTTLE_RATE", "10/minute"),
        # Per-IP anonymous signup POSTs; default allows retries/testing without opening unlimited abuse.
        "auth_signup": os.getenv("AUTH_SIGNUP_THROTTLE_RATE", "30/hour"),
        "auth_otp": os.getenv("AUTH_OTP_THROTTLE_RATE", "10/hour"),
        "auth_password_reset": os.getenv("AUTH_PASSWORD_RESET_THROTTLE_RATE", "8/hour"),
        "auth_token_refresh": os.getenv("AUTH_TOKEN_REFRESH_THROTTLE_RATE", "30/hour"),
        "public_write": os.getenv("PUBLIC_WRITE_THROTTLE_RATE", "20/hour"),
    },
}

# OpenAPI UI + /api/schema/ (set API_DOCS_ENABLED=true in env to enable in production).
API_DOCS_ENABLED = _parse_bool_env("API_DOCS_ENABLED", DEBUG)

SPECTACULAR_SETTINGS = {
    "TITLE": "BigChief API",
    "DESCRIPTION": "REST API documentation (machine-readable schema at /api/schema/).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "SIGNING_KEY": SECRET_KEY,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDISS_ADDRESS'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "ssl_cert_reqs": None,  # 🔥 THIS FIXES IT
            },
        }
    }
}

CACHES["default"]["OPTIONS"]["CONNECTION_POOL_KWARGS"]["ssl_cert_reqs"] = REDIS_SSL_CERT_REQS
CACHES["default"]["OPTIONS"]["CONNECTION_POOL_KWARGS"]["ssl_ca_certs"] = REDIS_SSL_CA_CERTS

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "payments": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "security.throttle": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "security.webhook": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

SENTRY_DSN = os.getenv("SENTRY_DSN")
SENTRY_ENABLED = _parse_bool_env("SENTRY_ENABLED", bool(SENTRY_DSN))
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0"))

if SENTRY_ENABLED and SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        send_default_pii=False,
    )

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

OTEL_INSTRUMENTATION_ENABLED = _parse_bool_env("OTEL_INSTRUMENTATION_ENABLED", True)

if OTEL_INSTRUMENTATION_ENABLED:
    DjangoInstrumentor().instrument()
